MediaDataApp/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :registros
  devise_for :users
  resources :users
  get 'users/show/:id' => 'user#show', :as => 'show_user_path'
  get 'static_pages/home'
  get 'export', to: 'registros#export', as: :registros_export
 

  root 'static_pages#home'

end

MediaDataApp/app/models/registro.rb
class Registro < ActiveRecord::Base
  belongs_to :user
  self.inheritance_column = nil

	def self.to_csv(registros_attributes = ['media','channel','h_inicio','h_final','location'],user_attributes = ['email'] ,options = {})
		CSV.generate(options) do |csv|
			csv.add_row registros_attributes + user_attributes 
			all.each do |registros|
				values = registros.attributes.slice(*registros_attributes).values
				if registros.user
					values += registros.user.attributes.slice(*user_attributes).values
				end
				csv.add_row values
			end
		end
	end

end

MediaDataApp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

 require 'carrierwave/orm/activerecord'
  has_many :registros
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :picture, PictureUploader
end

MediaDataApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?

   

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :age, :profession, :country, :picture, :current_password, :admin) }
    end
end

MediaDataApp/app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy]

  # GET /registros
  # GET /registros.json
  def index
    @registros = current_user.registros.all
  end

  def export
    @data = Registro.order(:created_at)
    respond_to do |format|
     format.html { redirect_to root_url }
     format.csv { send_data @data.to_csv }
    end
  end

  # GET /registros/1
  # GET /registros/1.json
  def show
  end

  # GET /registros/new
  def new
    @registro = Registro.new
    @cur_user = current_user.id;
  end

  # GET /registros/1/edit
  def edit
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(registro_params)
    @registro.user_id = current_user.id
    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro was successfully created.' }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registros/1
  # PATCH/PUT /registros/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to @registro, notice: 'Registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro.destroy
    respond_to do |format|
      format.html { redirect_to registros_url, notice: 'Registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro
      @registro = Registro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_params
      params.require(:registro).permit(:media, :channel, :h_inicio, :h_final, :location, :user_id)
    end
end

MediaDataApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
end

MediaDataApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	def index
		@users = User.all
    end
	def show
		 @user = User.find(params[:id])
		  respond_to do |format|
        	 format.html # show.html.erb
       		 format.xml { render :xml => @user }
    	end
	end
	def user_params
 		 params.require(:user).permit(:picture)
	end

	def edit
		#@users = User.all
	end

	def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    #redirect_to users;
  end

	def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:admin)
    end

end

MediaDataApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MediaDataApp/app/helpers/devise_helper.rb
    module DeviseHelper
     def devise_error_messages!
      return '' if resource.errors.empty?

       messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
       sentence = I18n.t('errors.messages.not_saved',
       count: resource.errors.count,
       resource: resource.class.model_name.human.downcase)

       html = <<-HTML
       <div class="alert  alert-danger  alert-block"> <button type="button"
        class="close" data-dismiss="alert">x</button>
        <h4>#{sentence}</h4>
        #{messages}
       </div>
       HTML

       html.html_safe
     end
    end

MediaDataApp/app/helpers/registros_helper.rb
module RegistrosHelper
end

MediaDataApp/app/helpers/users_helper.rb
module UsersHelper
end

MediaDataApp/app/views/layouts/_user_header.html.erb
 <header>
  <% if user_signed_in? %>

   <div class="menu_bar" data-step="1"  data-intro="Welcome to MediaData,let's start the tour!, if you want to exit it then press the skip button.">
  <a href="#" class="btn-menu" >
  <span class= "icon-menu" ></span>
  <%= image_tag("logo-technicolor2.png",:class => "img_preview")%>
  Media Data</a>
  </div>
  <nav>
    <ul>
     <li data-step="1" class="logo"  data-intro="Welcome to MediaData,let's start the tour!, if you want to exit it then press the skip button.">
          <%= image_tag("logo-technicolor2.png",:class => "img_preview1")%>
          
     </li>
     <li  data-step="2"  data-intro="By touching the home tab you can see your entries">
       <%= link_to root_path do %> 
        <span class="icon-home" ></span>
         Home
        <% end %>
     </li>
     <li data-step="4"  data-intro="By touching the New Entry tab you can create a new entry">
     <%= link_to new_registro_path do %> 
        <span class="icon-newentry"></span>
         New Entry
        <% end %>
     </li>
      <% if current_user.admin==true %>
        <li data-step="5"  data-intro="By touching the users tab you can see all the users on the app">
        <%= link_to users_index_path do %> 
        <span class="icon-users"></span>
         Users
        <% end %>
      <% end %>

      <% if current_user.admin==true %>
        <li data-step="6"  data-intro="By touching the export tab you can download all the entries in the app">
        <%= link_to registros_export_path(format: "csv") do %> 
        <span class="icon-cloud-download"></span>
         Export
        <% end %>
      <% end %>

      <li data-step="7"  data-intro="By touching the profile tab you can see your information">
        <%= link_to current_user do %> 
        <span class="icon-profile"></span>
         Profile
        <% end %>
     </li>
     <li data-step="8" data-position="right" data-intro="By touching the edit tab you can edit your information">
        <%= link_to edit_user_registration_path do %> 
        <span class="icon-settings"></span>
         Edit Profile
        <% end %>
     </li>
      <li>
        <%= link_to destroy_user_session_path, :method => :delete do %> 
        <span class="icon-signout"></span>
         Sign Out
        <% end %>
     </li>
    </ul>
  </nav>
<% end %>
</header>

MediaDataApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='mediadata'>
<head>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <title>MediaDataApp</title>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'fonts', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'estilos', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'introjs', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'intro', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body class="menu menu-open">


<div class="container-narrow">
    <script >
      if($(window).width()<= 800){
          $('nav').hide();
      }else{
          $('nav').show();
      }
    </script>
    <%= render 'layouts/user_header' %>
  
   <section>
       <%= yield %>
   </section>
   <script type="text/javascript"
   src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
   <%= javascript_include_tag 'menu', 'data-turbolinks-track' => true %>
   <script>
                $('.tour').click(function(){
                  introJs().start();
                });
                 
    </script>
</div>

</body>
</html>

MediaDataApp/app/views/registros/_form.html.erb
<div class="border-form-div">
  <%if current_user.registros.count == 0 %>
   <a class= "tour btn btn-success" align="center">Tutorial</a>
  <%end%>
<h1 align="center">New Entry</h1>
<%= form_for @registro do |f| %>
  <% if @registro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registro.errors.count, "error") %> prohibited this registro from being saved:</h2>

      <ul>
      <% @registro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :media %><br>
    <%= f.select :media, ["Internet","Television","Radio", "Movies","Newspaper"] ,:class =>"form-control"%>
  </div>
  <div class="field">
    <%= f.label :channel %><br>
    <%= f.text_field :channel %>
  </div>
  <div class="field">
    <%= f.label :h_inicio %><br>
    <%= f.time_select :h_inicio %>
  </div>
  <div class="field">
    <%= f.label :h_final %><br>
    <%= f.time_select :h_final %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.select :location, ["Home", "Work", "Other"] ,:class =>"form-control" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit "Create",:class =>'btn btn-primary' %>
  </div>
<% end %>
<%= link_to 'Show', @registro %> |
<%= link_to 'Back', registros_path %>
</div>
 

MediaDataApp/app/views/registros/edit.html.erb
<%= render 'form' %>

MediaDataApp/app/views/registros/index.html.erb
<div class="border-form-div">
<h1 align="center">Listing Entries</h1>
<% @registros.each do |registro| %>
     <div class="border-form-div">
       <label>Type: </label><%=registro.media %><br>
       <label>Channel: </label><%=registro.channel%><br>
       <label>Initial Hour: </label><%=registro.h_inicio.strftime("%I:%M%p")%><br>
       <label>Final Hour: </label><%=registro.h_final.strftime("%I:%M%p")%><br>
       <label>Location: </label><%=registro.location%><br>
       <%= link_to 'Edit', edit_registro_path(registro) %> 
     </div>
<% end %>
</div>

MediaDataApp/app/views/registros/new.html.erb
<%= render 'form' %>

MediaDataApp/app/views/registros/show.html.erb
<div class="border-form-div">

<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @registro.media %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @registro.channel %>
</p>

<p>
  <strong>H inicio:</strong>
  <%= @registro.h_inicio.strftime("%I:%M%p") %>
</p>

<p>
  <strong>H final:</strong>
  <%= @registro.h_final.strftime("%I:%M%p") %>
</p>

<p>
  <strong>Location:</strong>
  <%= @registro.location %>
</p>

<%= link_to 'Edit', edit_registro_path(@registro) %> |
<%= link_to 'Back', registros_path %>
</div>

MediaDataApp/app/views/static_pages/home.html.erb
  <% if user_signed_in? %>
       <%if current_user.registros.count == 0 %>
             
             
              <%= render :partial =>'registros/form', :locals => {:@registro => Registro.new} %>

        <%else%>
           <script type="text/javascript">
        window.location.href = "/registros"
        </script>
       <%end%>
  <% else %>
    
  <div class="jumbotron">
    <h1>Welcome!</h1>
    <p class="lead">
        Sign in to start making some new entries!!
    </p>
    <div class="row-fluid">
      
        <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
     
        <%= link_to "Registry", new_user_registration_path, :class => "btn btn-success" %>
    </div>
    </div>
  <% end %>

MediaDataApp/app/views/users/edit.html.erb
<div class="border-form-div">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.check_box :admin, :id=>'cb_admin', :style=>'visibility: hidden'%>      
  </div>
  <div id='pregunta'>
  </div>

  <div class="actions">
    <%= f.submit :value=>"Admin",:class =>'btn btn-primary',:id=>'link_admin' %>
  </div>
<% end %>
</div>
 

MediaDataApp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>NAME</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <% if  user.admin == true %>
          <td><%= link_to 'Remove Admin', edit_user_path(user),:class=>'link_admin' %></td>
        <%else %>
          <td><%= link_to 'Make Admin', edit_user_path(user), :class=>'link_admin'%></td>
        <% end %>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

MediaDataApp/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

MediaDataApp/app/views/users/show.html.erb
<div class="border-form-div">

<%= image_tag @user.picture_url(:thumb) %>

 <h1><%= @user.name %></h1>
 <%if @user.age !=nil %>
 	<label><%=:age%></label>
 	<h4><%= @user.age%></h4>
 <%end%>
 <%if @user.profession != nil%>
  <label><%=:profession%></label>
 <h4><%= @user.profession%></h4>
 <%end%>
 <%if @user.country != nil %>
  <label><%=:country%></label>
 <h4><%= @user.country%></h4>
 <%end%>
  <label><%=:email%></label>
 <h4><%= @user.email%></h4>
</div>